// <auto-generated />
using System;
using BorrowBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BorrowBuddy.Migrations
{
    [DbContext(typeof(BorrowBuddyContext))]
    partial class BorrowBuddyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BorrowBuddy.Domain.Currency", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Symbol");

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("BorrowBuddy.Domain.Flow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<long?>("LendeeId");

                    b.Property<long?>("LenderId");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("LendeeId");

                    b.HasIndex("LenderId");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("BorrowBuddy.Domain.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("BorrowBuddy.Domain.Flow", b =>
                {
                    b.HasOne("BorrowBuddy.Domain.Participant", "Lendee")
                        .WithMany()
                        .HasForeignKey("LendeeId");

                    b.HasOne("BorrowBuddy.Domain.Participant", "Lender")
                        .WithMany()
                        .HasForeignKey("LenderId");

                    b.OwnsOne("BorrowBuddy.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<long?>("FlowId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CurrencyCode");

                            b1.Property<int>("Value");

                            b1.HasIndex("CurrencyCode");

                            b1.ToTable("Flows");

                            b1.HasOne("BorrowBuddy.Domain.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyCode");

                            b1.HasOne("BorrowBuddy.Domain.Flow")
                                .WithOne("Amount")
                                .HasForeignKey("BorrowBuddy.Domain.Money", "FlowId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
