//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Currency
{
  code: string;
  symbol: string;
  scale: number;
}
export interface Flow
{
  id: string;
  lender: string;
  lendee: string;
  amount: number;
  currencyCode: string;
  currencyScale: number;
  comment: string;
  timestamp: string;
}
export interface FlowLog
{
  flow: Flow;
  lender: Participant;
  lendee: Participant;
}
export interface Participant
{
  id: string;
  firstName: string;
  middleName: string;
  lastName: string;
}
export interface FlowPost
{
  lender: string;
  lendee: string;
  amount: number;
  currencyCode: string;
  comment: string;
}
export interface ParticipantPost
{
  firstName: string;
  middleName: string;
  lastName: string;
}
